// Generates the Squarespace embed from the site's own source files, so the
// embed never drifts from what GitHub Pages serves. Run: node site/squarespace/build.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const SITE = join(HERE, "..");
const SCOPE = "#pingu-waitlist";

// Squarespace pages carry other ids; namespace ours so nothing collides.
const IDS = { thread: "pingu-thread", compose: "pingu-compose", email: "pingu-email", send: "pingu-send", stamp: "pingu-stamp" };

const read = (name) => readFileSync(join(SITE, name), "utf8");

function renameIds(text) {
  for (const [from, to] of Object.entries(IDS)) {
    text = text
      .replace(new RegExp(`id="${from}"`, "g"), `id="${to}"`)
      .replace(new RegExp(`for="${from}"`, "g"), `for="${to}"`)
      .replace(new RegExp(`getElementById\\("${from}"\\)`, "g"), `getElementById("${to}")`);
  }
  return text;
}

// Split a stylesheet into top-level chunks, keeping @-blocks whole.
function chunks(css) {
  const out = [];
  let depth = 0;
  let start = 0;
  for (let i = 0; i < css.length; i += 1) {
    if (css[i] === "{") depth += 1;
    else if (css[i] === "}") {
      depth -= 1;
      if (depth === 0) {
        out.push(css.slice(start, i + 1).trim());
        start = i + 1;
      }
    }
  }
  return out.filter(Boolean);
}

function prefixSelectors(list) {
  return list
    .split(",")
    .map((raw) => {
      const s = raw.trim();
      if (!s) return "";
      // The page's own root, html and body all become the embed wrapper.
      if (s === ":root" || s === "html" || s === "body") return SCOPE;
      if (s === "*") return `${SCOPE} *`;
      return `${SCOPE} ${s}`;
    })
    .filter(Boolean)
    .join(",\n");
}

function scope(css) {
  return chunks(css)
    .map((chunk) => {
      const open = chunk.indexOf("{");
      const head = chunk.slice(0, open).trim();
      const body = chunk.slice(open + 1, chunk.lastIndexOf("}"));
      // Keyframe percentages are not selectors; leave the block untouched.
      if (head.startsWith("@keyframes")) return chunk;
      if (head.startsWith("@media") || head.startsWith("@supports")) return `${head} {\n${scope(body)}\n}`;
      return `${prefixSelectors(head)} {${body}}`;
    })
    .join("\n\n");
}

const svgDataUri = `data:image/svg+xml;base64,${Buffer.from(read("pingu.svg")).toString("base64")}`;

const html = renameIds(read("index.html"));
const body = html.slice(html.indexOf("<body>") + "<body>".length, html.indexOf("</body>"))
  .replace(/<script src="app\.js"><\/script>/, "")
  .replace(/src="pingu\.svg"/g, `src="${svgDataUri}"`)
  .trim();

const css = scope(read("style.css").replace(/\/\*[\s\S]*?\*\//g, "").trim())
  .replace(/url\(pingu\.svg\)/g, `url(${svgDataUri})`);

const js = renameIds(read("app.js")).replace(/src="pingu\.svg"/g, `src="${svgDataUri}"`);

const embed = `<!-- Pingu waitlist. Generated by site/squarespace/build.mjs from site/index.html,
     style.css, app.js and pingu.svg. Edit those, re-run the script, re-paste. -->
<div id="pingu-waitlist">
<style>
/* This block only loads on the page that carries it. 100vw counts the
   scrollbar, so without the x-clip a full-bleed block adds a horizontal
   scrollbar on any page that scrolls vertically. */
html, body { overflow-x: hidden; }

${css}

/* Last, so it wins over the margin reset the page's own body rule became:
   breaks the block out of Squarespace's centred content column. */
${SCOPE} {
  position: relative;
  width: 100vw;
  max-width: 100vw;
  margin-left: calc(50% - 50vw);
  margin-right: calc(50% - 50vw);
  height: 100dvh;
  overflow: hidden;
  text-align: left;
}
</style>

${body}

<script>
${js}
</script>
</div>
`;

writeFileSync(join(HERE, "embed.html"), embed);
console.log(`embed.html written, ${(embed.length / 1024).toFixed(1)} KB`);
